# Use the official Maven image with OpenJDK 17 to build the application
FROM maven:3.8.1-openjdk-17 AS build
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn clean package

# Use the official OpenJDK 17 image to run the application
FROM openjdk:17-jdk-slim
WORKDIR /app
COPY --from=build /app/target/task-service-1.0-SNAPSHOT.jar app.jar
EXPOSE 8081
ENTRYPOINT ["java", "-jar", "app.jar"]
